spring:
  activiti:
    # 默认为true。为true表示activiti会对数据库中的表进行更新操作，如果不存在，则进行创建
    database-schema-update: true
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false # activti是否自动部署
    # 是否使用activiti中的act_id_*这4张表，默认true
    db-identity-used: true
    # 历史任务存储等级
    history-level: full
    # 开启历史记录表
    db-history-used: true
