server:
  port: 3001
#  servlet:
#    session:
#      timeout: 20s  # SpringBoot默认session超时是1分钟，小于1分钟还是1分钟
#      cookie:
#        http-only: true #这样设置就不能通过js脚本获取cookie
#        secure: true #只有https请求才会携带cookie


spring:
  application:
    name: cup
  security:
    loginType: JSON


  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/cup?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ENC(qPk24c9OuwPT2qYHnLIymA==)
    password: ENC(xz3XtbFndmSVOsS+CBxqrQ==)
    type: com.zaxxer.hikari.HikariDataSource
  main:
    allow-bean-definition-overriding: true

  # redis配置
  redis:
    host: localhost
    password:
    port: 6379

# token配置
token:
  header: 'Authorization'
  secret: '0123456789_0123456789_0123456789'
  expireTime: 30


# mybatis-plus配置
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    org.springframework.security: DEBUG



cup:
  # 是否开启演示模式
  enableDemo: false
  # 不校验token的请求
  token-ignore-url:
    - /tenant/list
    - /token/check
    - /token/refresh
    - /certification

  # 多租户配置
  tenant:
    enable: true
    ignore-tables:
#      - sys_menu

# jasypt安全框架—>盐值
jasypt:
  encryptor:
    password: mQjEGflOtK9YuwOS

