###########################################
#                                         #
#               主配置文件                 #
#                                         #
###########################################


server:
  port: 3001


spring:
  application:
    name: cup
  profiles:
    active: prod
  security:
    loginType: JSON
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  main:
    allow-bean-definition-overriding: true


# token配置
token:
  header: 'Authorization'
  secret: '0123456789_0123456789_0123456789'
  expireTime: 30


# mybatis-plus配置
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    org.springframework.security: DEBUG

cup:
  # 是否开启演示模式
  enableDemo: true
  # 验证码生成格式： math计算格式 char随机字符串
  captchaType: math
  # redis cache注解失效时间(单位：分)，默认60分钟
  cacheExpire: 60
  # 不校验token的请求
  token-ignore-url:
    - /tenant/list
    - /token/check
    - /token/refresh
    - /certification
    - /captcha/captchaImage

  # 多租户配置
  tenant:
    enable: true
    ignore-tables:
#      - sys_menu

# jasypt安全框架—>盐值
jasypt:
  encryptor:
    password: mQjEGflOtK9YuwOS


